Bugfix multiple secrets
fastify/session pull request #118
Opened 2022-08-12 14:21 UTC by rclmenezes

This PR is dependent on:
https://github.com/fastify/session/pull/117

Turns out, we were re-signing cookies with the new secret.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-08-12 14:22 UTC, rclmenezes commented
Benchmark:

```
$ node benchmark/bench.js
╔══════════════╤═════════╤═══════════════╤═══════════╤═════════════════════════╗
║ Slower tests │ Samples │        Result │ Tolerance │ Difference with slowest ║
╟──────────────┼─────────┼───────────────┼───────────┼─────────────────────────╢
║ file         │      25 │  31.31 op/sec │ ±  7.37 % │                         ║
║ redis        │      25 │ 109.38 op/sec │ ± 19.05 % │ + 249.38 %              ║
╟──────────────┼─────────┼───────────────┼───────────┼─────────────────────────╢
║ Fastest test │ Samples │        Result │ Tolerance │ Difference with slowest ║
╟──────────────┼─────────┼───────────────┼───────────┼─────────────────────────╢
║ memory       │      25 │ 815.79 op/sec │ ± 39.26 % │ + 2505.77 %             ║
╚══════════════╧═════════╧═══════════════╧═══════════╧═════════════════════════╝

✨  Done in 28.74s.
```

2022-08-12 15:58 UTC, rclmenezes commented on test/base.test.js
> -  })
Slightly unrelated -- this test doesn't need all of this and it's just distracting.

2022-08-12 16:01 UTC, rclmenezes commented on lib/session.js
> +      if (!['expires', 'cookie', 'encryptedSessionId'].includes(key)) {
The original PR had this change, which is why this bug came up

2022-08-12 16:22 UTC, rclmenezes commented on lib/session.js
> -    this[addDataToSession](prevSession)
I think this is extremely unreadable and buried. It caused me a lot of confusion earlier, so I decided to put in the function itself

2022-08-12 16:22 UTC, rclmenezes commented on test/base.test.js
> -  })
Slightly unrelated to the PR. All of this is outside the scope of the test.

2022-08-14 08:21 UTC, mcollina approved these changes
lgtm

2022-08-14 08:40 UTC, Uzlopak requested changes
Please dont merge yet. i want to review this more.

2022-08-15 15:43 UTC, Uzlopak commented
When #125 is merged, the cookie signing will be handled by @fastify/cookie, so we will not need to handled it in @fastify/session again...

2022-08-15 20:09 UTC, Uzlopak commented
Closing in favor of #125 and #127

2022-08-15 20:09 UTC, closed without merging