types: fix Session interface reference
fastify/session pull request #182
Opened 2022-12-22 20:00 UTC by FabianFrank

now Session actually resolves to the session interface defined in the same files instead of being an unresolved any

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

This doesn't require a new test/benchmark or doc change to the best of my knowledge.

2022-12-22 20:09 UTC, Uzlopak commented
Actually we could need a typing test

2022-12-22 20:32 UTC, FabianFrank commented
@Uzlopak there's already a typing test for this at https://github.com/fastify/session/blob/6462ff40acfad405f6898d9b4ee06890902d903a/types/types.test-d.ts#L92 and the test doesn't break with this change. it's unfortunate that the types work under test but not when installed as a dependency in another project. frankly, I'm not familiar enough with tsd to figure out how to make the test fail with `Fastify.Session`.

2022-12-22 20:35 UTC, Uzlopak commented
I will have a look later

2022-12-23 17:17 UTC, Eomm approved these changes

2022-12-23 22:41 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test? We use tsd for typescript.

2022-12-23 22:43 UTC, FabianFrank commented
@mcollina please see https://github.com/fastify/session/pull/182#issuecomment-1363317191

2022-12-24 14:43 UTC, mcollina commented
I'm uncomfortable in landing this without a test.

2022-12-24 17:56 UTC, FabianFrank commented
@mcollina how do you think the existing test for this type should change?

2022-12-25 22:36 UTC, mcollina commented
I don't know. I'm not the one proposing the change in this PR.

2022-12-26 16:21 UTC, climba03003 approved these changes
LGTM.

Let me explain a bit of the problem. 
The local assertion will always pass since as a package point, we know `Fastify` types before using it.
However, when it comes to the consumer. It will create an infinite loop of referencing. So, it will return `any` as a result.

For a test, we need to create a dummy package.json, install itself as dependent. Then, assertion the types inside the dummy package. Would it be too heavy as a test?

2022-12-26 19:46 UTC, FabianFrank commented
In https://github.com/fastify/session/issues/181#issuecomment-1365394199 we were able to track this down to the `esModuleInterop` setting in typescript, so to build on @climba03003's idea of a separate test package, we'd also have to make that test package an ESM module and disable module interop. Then the question is are we comfortable to only test the ESM case or do we want to test the CJS case as well, i.e. have 2 test packages?

2022-12-28 18:35 UTC, mcollina approved these changes
lgtm

2022-12-28 18:35 UTC, merged