Partitioned Bis (Fix Merge Conflict)
fastify/session pull request #226
Opened 2023-12-04 17:25 UTC by nicob-29

Related to https://github.com/fastify/session/issues/213

- [x] run `npm run test` and `npm run benchmark`
npm run benchmark -> failed
TypeError: redisStoreFactory is not a function
    at createServer (C:\GitHub\fastify-session\benchmark\bench.js:19:24)
    at testFunction (C:\GitHub\fastify-session\benchmark\bench.js:56:18)
    at main (C:\GitHub\fastify-session\benchmark\bench.js:83:15)

- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-04 17:28 UTC, Eomm reviewed
COuld you add a test?

2023-12-04 17:28 UTC, Eomm commented on package.json
> +  "version": "10.6.2",
Don't bump the version
We will take care of it

2023-12-04 17:28 UTC, Eomm commented on lib/cookie.js
> +    this.partitioned = cookie.partitioned ?? null
it seems a better default as the prop is trimmed away when serialized

```suggestion
    this.partitioned = cookie.partitioned ?? undefined
```

2023-12-04 17:32 UTC, nicob-29 commented on README.md
> +* `partitioned`- The `boolean` value of the `Partitioned` attribute. Using the Partitioned attribute as part of Cookies Having Independent Partitioned State (CHIPS) to allow cross-site access with a
it is already here: https://github.com/fastify/fastify-cookie

2023-12-04 18:50 UTC, gurgunday commented on lib/cookie.js
> +    this.partitioned = cookie.partitioned ?? undefined
nit: this means this for all practical purposes:

```suggestion
    this.partitioned = cookie.partitioned
```

2023-12-05 10:24 UTC, nicob-29 commented
@Eomm , Tests added

2023-12-05 10:30 UTC, Uzlopak commented on test/cookie.test.js
> +    t.equal('partitioned' in cookie, true)
Shouldnt it be:

```suggestion
    t.equal('partitioned' in json, true)
```

2023-12-05 13:49 UTC, Fdawgs requested changes
The PR title needs to be rewritten as it's not great in its current state. Won't make much sense to users reading release notes.

2023-12-05 13:59 UTC, gurgunday commented
What is wrong with this CI?

Rerunning

2023-12-05 14:10 UTC, gurgunday approved these changes

2023-12-06 16:52 UTC, gurgunday commented
It's not enabled by default?

Also, I wonder why we're not using fastify/cookie here

2023-12-06 16:53 UTC, gurgunday commented
And we might want to label it as experimental or non-standard

2023-12-06 16:55 UTC, gurgunday commented on README.md
> +* `partitioned`- The `boolean` value of the `Partitioned` attribute. Using the Partitioned attribute as part of Cookies Having Independent Partitioned State (CHIPS) to allow cross-site access with a
```suggestion
* `partitioned` (**experimental**) - The `boolean` value of the `Partitioned` attribute. Using the Partitioned attribute as part of Cookies Having Independent Partitioned State (CHIPS) to allow cross-site access with a separate cookie used per site. Defaults to false.
```

2023-12-06 19:27 UTC, jsumners commented
I am completely against making a draft proposal the default implementation of anything.

2023-12-06 23:03 UTC, gurgunday commented
Yeah me too, the title is wrong, the PR just adds `partitioned`, it doesn't make it the default

2023-12-08 07:13 UTC, Fdawgs approved these changes

2023-12-08 09:39 UTC, mcollina approved these changes
lgtm

2023-12-08 09:39 UTC, merged

2023-12-08 14:09 UTC, nicob-29 commented
Thank you everyone !