feat: session cookie opts
fastify/session pull request #53
Opened 2022-01-07 16:23 UTC by zbo14

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

--

Addresses #17

Also, see [this](https://github.com/fastify/help/issues/511) issue and [this](https://github.com/SerayaEryn/fastify-session/issues/106) one.

There are certain cases where the developer might want cookie options specific to a particular session, e.g. set `maxAge` if this user checked "remember me". This PR adds a `cookieOpts` argument to the `decryptSession` decorator so the developer can manually specify cookie parameters on a per-session basis using whatever business logic they so choose.

2022-01-08 11:25 UTC, mcollina commented
What's missing in this PR? It's still a draft.

Good work!

2022-01-10 15:15 UTC, zbo14 commented
@zekth would really appreciate a review if you have time :)

2022-01-10 17:28 UTC, mcollina approved these changes
lgtm

2022-01-10 18:14 UTC, zekth requested changes
Just a minor comment.

2022-01-10 18:14 UTC, zekth commented on lib/fastifySession.js
> +    if (typeof cookieOpts === 'function') {
Could you please add a comment why this is done this way? Mention the deprecation of the method.

2022-01-11 15:55 UTC, zekth approved these changes
:v: thanks

2022-01-12 09:22 UTC, merged